FROM debian:bookworm

# Outils de base (python3, venv, node, npm)
RUN apt-get update && \
    apt-get install -y python3 python3-venv python3-pip nodejs npm

# Copier le Makefile (+ optionnellement les backend/frontend)
WORKDIR /work

# Active le dev-env via Makefile
CMD ["make", "dev"]